"""Template-constrained LLM safety layer (Task 11.10).

This is the guardrail stage of the Insights & ML Service's "LLM Insight Layer"
(design: "LLM Insight Layer"). Insight/recommendation content is generated by a
template-constrained model grounded strictly on the user's own data; before any
content is ever shown it must pass through the three deterministic, pure gates
implemented here:

1. **Approval filtering (Req 13.3, 29.3, 29.4)** — only content whose clinical
   advisory board ``approval_status`` is exactly ``"approved"`` is eligible.
   Draft, pending, and revoked content is always excluded. When *nothing*
   eligible remains, a "no guidance available" message is surfaced (Req 13.5)
   and the underlying reading data is left untouched (these functions never
   mutate readings — Req 29.4).

2. **Diagnostic-term exclusion (Req 29.1)** — v1.0 is general-wellness only, so
   any content containing a disallowed diagnostic claim, medical condition name,
   or treatment recommendation (see :data:`DISALLOWED_TERMS`) is withheld.

3. **Mandatory disclaimer rendering (Req 29.2, 29.5)** — every displayed insight
   must carry a rendered wellness disclaimer within the same view. If the
   disclaimer cannot be rendered (``disclaimer_rendered`` is False), the insight
   is withheld and an "unavailable" indication is shown instead.

The whole pipeline is a pure function over plain values so it is directly
unit-testable and a FastAPI route (or the guidance engine of Task 11.7) can bind
to it without any I/O. Ordering of both displayed and withheld collections is
the input order, so results are deterministic.

This module is intentionally self-contained (Task 11.10 scope): correlation /
significance (Task 11.1), recurring-pattern & milestone ranking (Task 11.4),
the readiness-gated guidance engine (Task 11.7), and the weekly digest
(Task 11.14) live in their own modules and are not touched here.

Requirements: 13.3, 13.5, 29.1, 29.2, 29.3, 29.4, 29.5
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Optional, Sequence, Tuple

from cc_contracts.domain import Insight

# ---------------------------------------------------------------------------
# Constants: canonical disclaimer, user-facing messages, disallowed terms
# ---------------------------------------------------------------------------

#: Canonical wellness disclaimer rendered within the same view as every insight
#: (Req 29.2). The exact copy is a product/legal decision; this is the default.
WELLNESS_DISCLAIMER: str = (
    "This information is general-wellness guidance and is not a medical "
    "diagnosis. Consult a qualified healthcare professional for medical advice."
)

#: Shown when no clinically approved template matches (Req 13.5 / 29.4).
NO_GUIDANCE_AVAILABLE_MESSAGE: str = "No guidance is currently available."

#: Shown in place of an insight whose disclaimer could not be rendered (Req 29.5).
INSIGHT_UNAVAILABLE_MESSAGE: str = "This insight is currently unavailable."

# Reason codes explaining why a candidate was withheld from display.
REASON_NOT_APPROVED: str = "not_approved"
REASON_DISALLOWED_TERMS: str = "disallowed_terms"
REASON_DISCLAIMER_UNAVAILABLE: str = "disclaimer_unavailable"

#: The one approval state that permits display (Req 13.3 / 29.3).
APPROVED_STATUS: str = "approved"

#: Disallowed v1.0 language: diagnostic claims, medical condition names, and
#: treatment recommendations (Req 29.1). Matching is case-insensitive and
#: word-boundary anchored, so multi-word phrases (e.g. "adrenal fatigue") and
#: possessives (e.g. "cushing's") are matched as whole terms and substrings of
#: benign words are not (e.g. "cure" does not match "manicure"). Callers may
#: pass their own set to :func:`apply_safety_filter` to extend or override it.
DISALLOWED_TERMS: Tuple[str, ...] = (
    # --- Diagnostic claims ---
    "diagnosis",
    "diagnose",
    "diagnosed",
    "diagnostic",
    "disease",
    "disorder",
    "syndrome",
    "pathology",
    "condition",
    # --- Medical condition names ---
    "cushing",
    "cushing's",
    "addison",
    "addison's",
    "hypercortisolism",
    "hypocortisolism",
    "adrenal insufficiency",
    "adrenal fatigue",
    "hypertension",
    "diabetes",
    "hypothyroidism",
    "hyperthyroidism",
    "depression",
    "tumor",
    "tumour",
    "cancer",
    # --- Treatment recommendations ---
    "prescribe",
    "prescribed",
    "prescription",
    "medication",
    "medicate",
    "dose",
    "dosage",
    "drug",
    "treat",
    "treatment",
    "therapy",
    "cure",
    "steroid",
    "hydrocortisone",
    "cortisone",
)


# ---------------------------------------------------------------------------
# Inputs / outputs
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CandidateInsight:
    """A generated insight paired with its rendered content text.

    The :class:`~cc_contracts.domain.Insight` carries the approval status,
    disclaimer-rendered flag, and rank score; ``content`` is the template-
    constrained text produced for the user. Both are needed by the safety gates:
    ``content`` is scanned for disallowed diagnostic language (Req 29.1) while
    the insight's ``approval_status`` and ``disclaimer_rendered`` drive the
    approval and disclaimer gates.
    """

    insight: Insight
    content: str


@dataclass(frozen=True)
class DisplayedInsight:
    """An insight cleared for display, with its disclaimer rendered in-view."""

    insight: Insight
    content: str
    disclaimer: str


@dataclass(frozen=True)
class WithheldInsight:
    """An insight excluded from display, with the reason and user indication."""

    insight: Insight
    reason: str
    indication: str
    matched_terms: Tuple[str, ...] = ()


@dataclass(frozen=True)
class SafetyFilterResult:
    """Outcome of the safety pipeline.

    ``displayed`` are insights that passed every gate (each carries a rendered
    disclaimer). ``withheld`` explains every excluded candidate. ``message`` is
    set to :data:`NO_GUIDANCE_AVAILABLE_MESSAGE` exactly when nothing is
    displayable, and is ``None`` otherwise (Req 13.5).
    """

    displayed: Tuple[DisplayedInsight, ...] = field(default_factory=tuple)
    withheld: Tuple[WithheldInsight, ...] = field(default_factory=tuple)
    message: Optional[str] = None

    @property
    def has_guidance(self) -> bool:
        """True iff at least one insight is displayable."""
        return len(self.displayed) > 0


# ---------------------------------------------------------------------------
# Gate 1: approval filtering (Req 13.3, 29.3, 29.4)
# ---------------------------------------------------------------------------


def is_approved(insight: Insight) -> bool:
    """Whether an insight's approval status permits display.

    Only the exact status ``"approved"`` is eligible; ``draft``, ``pending``,
    and ``revoked`` are all excluded (Req 13.3 / 29.3 / 29.4).
    """
    return insight.approval_status == APPROVED_STATUS


# ---------------------------------------------------------------------------
# Gate 2: diagnostic / condition / treatment term exclusion (Req 29.1)
# ---------------------------------------------------------------------------


def _term_pattern(term: str) -> "re.Pattern[str]":
    """Compile a case-insensitive, word-boundary matcher for one disallowed term."""
    return re.compile(r"\b" + re.escape(term.lower()) + r"\b")


def find_disallowed_terms(
    content: str, disallowed_terms: Sequence[str] = DISALLOWED_TERMS
) -> Tuple[str, ...]:
    """Return the disallowed terms present in ``content`` (deduped, sorted).

    Matching is case-insensitive and anchored on word boundaries, so a term only
    matches when it appears as a whole word/phrase (Req 29.1).
    """
    text = content.lower()
    found = {term for term in disallowed_terms if _term_pattern(term).search(text)}
    return tuple(sorted(found))


def contains_disallowed_language(
    content: str, disallowed_terms: Sequence[str] = DISALLOWED_TERMS
) -> bool:
    """Whether ``content`` contains any disallowed diagnostic language (Req 29.1)."""
    return len(find_disallowed_terms(content, disallowed_terms)) > 0


# ---------------------------------------------------------------------------
# Gate 3: mandatory disclaimer rendering (Req 29.2, 29.5)
# ---------------------------------------------------------------------------


def can_render_disclaimer(insight: Insight) -> bool:
    """Whether a wellness disclaimer can be rendered for this insight (Req 29.2)."""
    return bool(insight.disclaimer_rendered)


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------


def apply_safety_filter(
    candidates: Sequence[CandidateInsight],
    *,
    disallowed_terms: Sequence[str] = DISALLOWED_TERMS,
    disclaimer: str = WELLNESS_DISCLAIMER,
) -> SafetyFilterResult:
    """Filter candidate insights through the three safety gates, in order.

    For each candidate, in input order:

    1. If not ``approved`` → withhold (``REASON_NOT_APPROVED``). Req 13.3/29.3/29.4.
    2. Else if the content contains disallowed diagnostic/condition/treatment
       language → withhold (``REASON_DISALLOWED_TERMS``). Req 29.1.
    3. Else if the disclaimer cannot be rendered → withhold
       (``REASON_DISCLAIMER_UNAVAILABLE``) with an unavailable indication.
       Req 29.2/29.5.
    4. Else → display, with the disclaimer attached in-view. Req 29.2.

    When nothing is displayable, ``message`` is set to
    :data:`NO_GUIDANCE_AVAILABLE_MESSAGE` (Req 13.5). Reading data is never
    touched by this pure function (Req 29.4). The result is deterministic:
    displayed and withheld both follow input order.
    """
    displayed: List[DisplayedInsight] = []
    withheld: List[WithheldInsight] = []

    for candidate in candidates:
        insight = candidate.insight

        if not is_approved(insight):
            withheld.append(
                WithheldInsight(
                    insight=insight,
                    reason=REASON_NOT_APPROVED,
                    indication=NO_GUIDANCE_AVAILABLE_MESSAGE,
                )
            )
            continue

        matched = find_disallowed_terms(candidate.content, disallowed_terms)
        if matched:
            withheld.append(
                WithheldInsight(
                    insight=insight,
                    reason=REASON_DISALLOWED_TERMS,
                    indication=INSIGHT_UNAVAILABLE_MESSAGE,
                    matched_terms=matched,
                )
            )
            continue

        if not can_render_disclaimer(insight):
            withheld.append(
                WithheldInsight(
                    insight=insight,
                    reason=REASON_DISCLAIMER_UNAVAILABLE,
                    indication=INSIGHT_UNAVAILABLE_MESSAGE,
                )
            )
            continue

        displayed.append(
            DisplayedInsight(
                insight=insight, content=candidate.content, disclaimer=disclaimer
            )
        )

    message = None if displayed else NO_GUIDANCE_AVAILABLE_MESSAGE
    return SafetyFilterResult(
        displayed=tuple(displayed), withheld=tuple(withheld), message=message
    )
