/**
 * Conversation History — Types
 *
 * Request shapes, the workspace access-control seam, and the dependency-injection
 * contract for the Conversation History service (record and list).
 *
 * The Conversation History service records each Q&A entry produced by the
 * Query_Engine and exposes a workspace's history to authorized members ordered
 * most-recent-first.
 *
 * Validates: Requirements 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7
 */

import type {
  Answer,
  BaseServiceDependencies,
  ConversationEntry,
  ConversationRepository,
  UserRef,
} from '../api-copilot-shared';
import type { AccessDecision } from '../workspace';

// ---------------------------------------------------------------------------
// Timing & retention constants
// ---------------------------------------------------------------------------

/**
 * Performance target for recording a Conversation_History entry after an answer
 * is produced (Req 15.1). The in-memory path completes well within this bound;
 * the constant documents the contract for production repository adapters.
 */
export const RECORD_DEADLINE_MS = 2000;

/**
 * Minimum retention period for a Conversation_History entry, measured from the
 * time the answer was produced (Req 15.7). Entries younger than this MUST NOT be
 * removed; entries older than this MAY be pruned.
 */
export const RETENTION_MINIMUM_DAYS = 365;

/** {@link RETENTION_MINIMUM_DAYS} expressed in milliseconds. */
export const RETENTION_MINIMUM_MS = RETENTION_MINIMUM_DAYS * 24 * 60 * 60 * 1000;

// ---------------------------------------------------------------------------
// Request shapes
// ---------------------------------------------------------------------------

/**
 * A new Q&A entry to record. This is the integration seam the Query_Engine
 * (`QueryEngine.ask`, task 8.1) calls immediately after producing an answer:
 * it supplies the owning workspace, the identity of the user who submitted the
 * question, the question text, and the produced answer.
 *
 * `answeredAt` is optional — when omitted the service stamps the entry with the
 * injected clock so the recorded time reflects when the answer was produced
 * (Req 15.6). The entry identifier is always generated by the service.
 */
export interface NewConversationEntry {
  workspaceId: string;
  /** Identity of the user who submitted the question (Req 15.6). */
  userId: string;
  question: string;
  answer: Answer;
  /** Time the answer was produced; defaults to the injected clock (Req 15.6). */
  answeredAt?: Date;
}

// ---------------------------------------------------------------------------
// Workspace access-control seam — Req 15.4
// ---------------------------------------------------------------------------

/**
 * Access-control seam used by conversation reads. It is satisfied structurally
 * by {@link WorkspaceService.authorize}, so the composition root can wire the
 * authoritative Workspace service while tests inject a fake. Reusing the
 * Workspace domain's decision keeps conversation isolation identical to
 * workspace isolation (Req 14.3, 15.4).
 */
export interface WorkspaceAuthorizer {
  authorize(
    requester: UserRef,
    workspaceId: string
  ): AccessDecision | Promise<AccessDecision>;
}

// ---------------------------------------------------------------------------
// Dependency injection — extends the shared base (idGenerator, dateProvider)
// ---------------------------------------------------------------------------

/**
 * Dependencies for {@link ConversationService}. Supplied as a
 * `Partial<ConversationDependencies>`; anything omitted falls back to an
 * in-memory / default implementation.
 */
export interface ConversationDependencies extends BaseServiceDependencies {
  conversationRepository: ConversationRepository;
  /** Resolves whether a requester may read a workspace's history (Req 15.4). */
  workspaceAuthorizer: WorkspaceAuthorizer;
}

export type { ConversationEntry, UserRef };
