"""cc_contracts — shared domain types and API contracts for the Python services.

Python mirror of the TypeScript source of truth (`@calorie-cortisol/shared`).
Used by the Food Vision, Nutrition Lookup, and Insights & ML services so all
services share the same contracts (design: Data Models).

Implemented in task 1.2 ("Define shared domain types and API contracts").
"""

from cc_contracts import constants, contracts, domain, guards
from cc_contracts.domain import (
    AlignedPair,
    ApprovalStatus,
    AuditAction,
    AuditEntry,
    BoundingBox,
    BurdenTier,
    CARMeasurement,
    CARSample,
    Classification,
    ConsentState,
    Correction,
    CorrelationResult,
    CortisolReading,
    CortisolSource,
    FamilyAccount,
    FamilyRole,
    FoodItem,
    Insight,
    LifeEvent,
    Meal,
    MealItem,
    MealSource,
    MemberProfile,
    NutrientUnit,
    NutrientValue,
    NutritionTotals,
    PlateCalibration,
    PortionEstimate,
    QuestionnaireResult,
    QuestionnaireType,
    ReferenceContext,
    ReferenceObject,
    Residency,
    Sex,
    SyncStatus,
    TimeOfDayBucket,
)

PACKAGE_NAME = "cc_contracts"

__all__ = [
    "PACKAGE_NAME",
    "constants",
    "contracts",
    "domain",
    "guards",
    "AlignedPair",
    "ApprovalStatus",
    "AuditAction",
    "AuditEntry",
    "BoundingBox",
    "BurdenTier",
    "CARMeasurement",
    "CARSample",
    "Classification",
    "ConsentState",
    "Correction",
    "CorrelationResult",
    "CortisolReading",
    "CortisolSource",
    "FamilyAccount",
    "FamilyRole",
    "FoodItem",
    "Insight",
    "LifeEvent",
    "Meal",
    "MealItem",
    "MealSource",
    "MemberProfile",
    "NutrientUnit",
    "NutrientValue",
    "NutritionTotals",
    "PlateCalibration",
    "PortionEstimate",
    "QuestionnaireResult",
    "QuestionnaireType",
    "ReferenceContext",
    "ReferenceObject",
    "Residency",
    "Sex",
    "SyncStatus",
    "TimeOfDayBucket",
]
